{
  BurdockPaint - Copyright 2023 MKSZTSZ
  Written by Szabó "Gilby" Zsolt / MKSZTSZ

  This file is part of the source code of BurdockPaint.

  BurdockPaint is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by the
  Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  BurdockPaint is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU General Public License for more details.

  You should have received a copy of the GNU General Public License along with
  BurdockPaint. If not, see <https://www.gnu.org/licenses/>.
}

// Menu message constants.
// Generated on 2023.05.23.

const
  MSG_NEWPROJECT=200;
  MSG_OPENPROJECT=201;
  MSG_SAVEPROJECT=202;
  MSG_SAVECLEARPROJECT=203;
  MSG_NEWIMAGE=204;
  MSG_OPENIMAGE=205;
  MSG_SAVEIMAGE=206;
  MSG_REMOVEIMAGE=207;
  MSG_CLEARIMAGE=208;
  MSG_GETCEL=209;
  MSG_PUTCEL=210;
  MSG_RELEASECEL=211;
  MSG_OPENROTATECELDIALOG=212;
  MSG_FLIPCEL=213;
  MSG_OPENMAGNIFYCELDIALOG=214;
  MSG_OPENCEL=215;
  MSG_SAVECEL=216;
  MSG_EXPORTCEL=217;
  MSG_RAMPCLUSTER=218;
  MSG_TOOLDRAW=219;
  MSG_TOOLBOX=220;
  MSG_TOOLLINE=221;
  MSG_TOOLCIRCLE=222;
  MSG_TOOLFILL=223;
  MSG_TOOLFILLTO=224;
  MSG_TOOLSEP=225;
  MSG_INKOPAQUE=226;
  MSG_INKHGRAD=227;
  MSG_INKVGRAD=228;
  MSG_INKLGRAD=229;
  MSG_INKRGRAD=230;
  MSG_INKRANDOM=231;
  MSG_INKSOFTEN=232;
  MSG_OPENABOUTDIALOG=233;
